version: '1.0'
services:
  api:
    build: ./server
    container_name: 2048_duel-server
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - ./server:/node_modules
  client:
    build: ./client
    container_name: 2048_duel-client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client:/node_modules
    stdin_open: true
    tty: true